// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UP_Ilya.Models;

public partial class UserShow
{
    public string TVShowName { get; set; }

    public string UserName { get; set; }

    public string UserRole { get; set; }
}