// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UP_Ilya.Models;

public partial class Watcher_TV_Show
{
    public int WatcherTVShowID { get; set; }

    public int WatcherID { get; set; }

    public int TVShowID { get; set; }

    public virtual TV_Show TVShow { get; set; }

    public virtual Watcher Watcher { get; set; }
}